version: '3'

services:
  strfry-nostr-relay:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /home/ubuntu/strfry/strfry.conf:/etc/strfry.conf
      - /home/ubuntu/strfry/strfry-db/:/app/strfry-db
    ports:
      - "7777:7777"
    user: "root"
    restart: always
